apiVersion: apps/v1
kind: Deployment
metadata:
  name: fashion-service
  namespace: microservices-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fashion-service
  template:
    metadata:
      labels:
        app: fashion-service
    spec:
      containers:
        - name: fashion-service
          image: fashion-service:latest
          ports:
            - containerPort: 5003