apiVersion: v1
kind: Service
metadata:
  name: fashion-service
  namespace: microservices-app
spec:
  selector:
    app: fashion-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003